const mockData = [
  {
    created_at: "Mon Apr 19 18:06:42 +0000 2021",
    id: 1384206838376272000,
    id_str: "1384206838376271872",
    full_text:
      "Twitter Out Loud reads your Twitter feed, just like this, using the Web Speech API SpeechSynthesis interface.",
    truncated: false,
    display_text_range: [0, 109],
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [],
      urls: [],
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 1383798920824852500,
      id_str: "1383798920824852601",
      name: "Nick 🎓",
      screen_name: "nickmeisenhaus",
      location: "Kitchener, ON",
      description: "Web Developer, Dad",
      url: null,
      entities: {
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 3,
      friends_count: 13,
      listed_count: 0,
      created_at: "Sun Apr 18 15:05:58 +0000 2021",
      favourites_count: 1,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 1,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "F5F8FA",
      profile_background_image_url: null,
      profile_background_image_url_https: null,
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1384204416194998277/xkldGlZs_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1384204416194998277/xkldGlZs_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/1383798920824852601/1618855163",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: false,
      following: true,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none",
      withheld_in_countries: [],
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: "en",
  },
  {
    created_at: "Mon Apr 19 18:11:48 +0000 2021",
    id: 1384208121149616000,
    id_str: "1384208121149616141",
    full_text:
      "Don’t like the sound of this voice? Change it! Let’s take a quick look at the options you have to control the timbre of the voice.",
    truncated: false,
    display_text_range: [0, 130],
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [],
      urls: [],
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 1379970996350947300,
      id_str: "1379970996350947335",
      name: "Saïd",
      screen_name: "sredouane10",
      location: "",
      description: "",
      url: null,
      entities: {
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 2,
      friends_count: 10,
      listed_count: 0,
      created_at: "Thu Apr 08 01:35:11 +0000 2021",
      favourites_count: 0,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 5,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "F5F8FA",
      profile_background_image_url: null,
      profile_background_image_url_https: null,
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1384202985639604226/-qUtqxKk_normal.png",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1384202985639604226/-qUtqxKk_normal.png",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: false,
      following: true,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none",
      withheld_in_countries: [],
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: "en",
  },
  {
    created_at: "Mon Apr 19 18:11:35 +0000 2021",
    id: 1384208069861675000,
    id_str: "1384208069861675013",
    full_text:
      "We enjoy Twitter in two ways; firstly reading our timelines to get new information for multiple sources, and secondly by taking the time to dig into specific interesting threads. So we built the same functionality into Twitter Out Loud, with dedicated timeline and thread modes",
    truncated: false,
    display_text_range: [0, 277],
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [],
      urls: [],
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 1350939104444371000,
      id_str: "1350939104444370945",
      name: "Dan",
      screen_name: "danpappo",
      location: "",
      description:
        "Building software for the web, science and healthcare data, good jokes | Coding bootcamp student #CodingBootcamp, Habit stacker | 🥳 | 📬 DMs open",
      url: "https://t.co/7UhEg21PHp",
      entities: {
        url: {
          urls: [
            {
              url: "https://t.co/7UhEg21PHp",
              expanded_url: "https://github.com/dpappo",
              display_url: "github.com/dpappo",
              indices: [0, 23],
            },
          ],
        },
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 9,
      friends_count: 19,
      listed_count: 0,
      created_at: "Sun Jan 17 22:52:44 +0000 2021",
      favourites_count: 14,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 36,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "F5F8FA",
      profile_background_image_url: null,
      profile_background_image_url_https: null,
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1350939215836680195/rVqUYoi8_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1350939215836680195/rVqUYoi8_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/1350939104444370945/1617801337",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: false,
      following: true,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none",
      withheld_in_countries: [],
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: "en",
  },
  {
    created_at: "Mon Apr 19 18:11:45 +0000 2021",
    id: 1384208108356915200,
    id_str: "1384208108356915202",
    full_text:
      "We found that Twitter’s API didn’t have native support for displaying recent threads, so we built out a custom complex algorithm to organize the data for our users",
    truncated: false,
    display_text_range: [0, 163],
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [],
      urls: [],
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 1350939104444371000,
      id_str: "1350939104444370945",
      name: "Dan",
      screen_name: "danpappo",
      location: "",
      description:
        "Building software for the web, science and healthcare data, good jokes | Coding bootcamp student #CodingBootcamp, Habit stacker | 🥳 | 📬 DMs open",
      url: "https://t.co/7UhEg21PHp",
      entities: {
        url: {
          urls: [
            {
              url: "https://t.co/7UhEg21PHp",
              expanded_url: "https://github.com/dpappo",
              display_url: "github.com/dpappo",
              indices: [0, 23],
            },
          ],
        },
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 9,
      friends_count: 19,
      listed_count: 0,
      created_at: "Sun Jan 17 22:52:44 +0000 2021",
      favourites_count: 14,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 36,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "F5F8FA",
      profile_background_image_url: null,
      profile_background_image_url_https: null,
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1350939215836680195/rVqUYoi8_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1350939215836680195/rVqUYoi8_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/1350939104444370945/1617801337",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: false,
      following: true,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none",
      withheld_in_countries: [],
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: "en",
  },
  {
    created_at: "Mon Apr 19 18:11:52 +0000 2021",
    id: 1384208137612251100,
    id_str: "1384208137612251140",
    full_text:
      "Our algorithm triangulates between 3 different APIs to gather and process the right data in the right order",
    truncated: false,
    display_text_range: [0, 107],
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [],
      urls: [],
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: 1384208108356915200,
    in_reply_to_status_id_str: "1384208108356915202",
    in_reply_to_user_id: 1350939104444371000,
    in_reply_to_user_id_str: "1350939104444370945",
    in_reply_to_screen_name: "danpappo",
    user: {
      id: 1350939104444371000,
      id_str: "1350939104444370945",
      name: "Dan",
      screen_name: "danpappo",
      location: "",
      description:
        "Building software for the web, science and healthcare data, good jokes | Coding bootcamp student #CodingBootcamp, Habit stacker | 🥳 | 📬 DMs open",
      url: "https://t.co/7UhEg21PHp",
      entities: {
        url: {
          urls: [
            {
              url: "https://t.co/7UhEg21PHp",
              expanded_url: "https://github.com/dpappo",
              display_url: "github.com/dpappo",
              indices: [0, 23],
            },
          ],
        },
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 9,
      friends_count: 19,
      listed_count: 0,
      created_at: "Sun Jan 17 22:52:44 +0000 2021",
      favourites_count: 14,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 36,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "F5F8FA",
      profile_background_image_url: null,
      profile_background_image_url_https: null,
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1350939215836680195/rVqUYoi8_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1350939215836680195/rVqUYoi8_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/1350939104444370945/1617801337",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: false,
      following: true,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none",
      withheld_in_countries: [],
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: "en",
  },
  {
    created_at: "Mon Apr 19 18:12:00 +0000 2021",
    id: 1384208173662302200,
    id_str: "1384208173662302212",
    full_text:
      "This way, users can listen to thoughtful ideas and stories in a sequential and logical flow 🧵",
    truncated: false,
    display_text_range: [0, 93],
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [],
      urls: [],
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: 1384208137612251100,
    in_reply_to_status_id_str: "1384208137612251140",
    in_reply_to_user_id: 1350939104444371000,
    in_reply_to_user_id_str: "1350939104444370945",
    in_reply_to_screen_name: "danpappo",
    user: {
      id: 1350939104444371000,
      id_str: "1350939104444370945",
      name: "Dan",
      screen_name: "danpappo",
      location: "",
      description:
        "Building software for the web, science and healthcare data, good jokes | Coding bootcamp student #CodingBootcamp, Habit stacker | 🥳 | 📬 DMs open",
      url: "https://t.co/7UhEg21PHp",
      entities: {
        url: {
          urls: [
            {
              url: "https://t.co/7UhEg21PHp",
              expanded_url: "https://github.com/dpappo",
              display_url: "github.com/dpappo",
              indices: [0, 23],
            },
          ],
        },
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 9,
      friends_count: 19,
      listed_count: 0,
      created_at: "Sun Jan 17 22:52:44 +0000 2021",
      favourites_count: 14,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 36,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "F5F8FA",
      profile_background_image_url: null,
      profile_background_image_url_https: null,
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1350939215836680195/rVqUYoi8_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1350939215836680195/rVqUYoi8_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/1350939104444370945/1617801337",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: false,
      following: true,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none",
      withheld_in_countries: [],
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: "en",
  },
  {
    created_at: "Mon Apr 19 18:12:05 +0000 2021",
    id: 1384208195070038000,
    id_str: "1384208195070038016",
    full_text:
      "We wanted to ensure that we developed a solution that would abide to accessibility trends and would run with minimal on-screen user input, so we built out a Voice User Interface to allow users to interact with the app hands free.",
    truncated: false,
    display_text_range: [0, 229],
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [],
      urls: [],
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 1379970996350947300,
      id_str: "1379970996350947335",
      name: "Saïd",
      screen_name: "sredouane10",
      location: "",
      description: "",
      url: null,
      entities: {
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 2,
      friends_count: 10,
      listed_count: 0,
      created_at: "Thu Apr 08 01:35:11 +0000 2021",
      favourites_count: 0,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 5,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "F5F8FA",
      profile_background_image_url: null,
      profile_background_image_url_https: null,
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1384202985639604226/-qUtqxKk_normal.png",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1384202985639604226/-qUtqxKk_normal.png",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: false,
      following: true,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none",
      withheld_in_countries: [],
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: "en",
  },
  {
    created_at: "Mon Apr 19 23:04:51 +0000 2021",
    id: 1384281872344047600,
    id_str: "1384281872344047617",
    full_text:
      "A single click to Activate Voice commands allows our users to interact with the app using their voice",
    truncated: false,
    display_text_range: [0, 101],
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [],
      urls: [],
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: 1384208195070038000,
    in_reply_to_status_id_str: "1384208195070038016",
    in_reply_to_user_id: 1379970996350947300,
    in_reply_to_user_id_str: "1379970996350947335",
    in_reply_to_screen_name: "sredouane10",
    user: {
      id: 1379970996350947300,
      id_str: "1379970996350947335",
      name: "Saïd",
      screen_name: "sredouane10",
      location: "",
      description: "",
      url: null,
      entities: {
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 2,
      friends_count: 10,
      listed_count: 0,
      created_at: "Thu Apr 08 01:35:11 +0000 2021",
      favourites_count: 0,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 5,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "F5F8FA",
      profile_background_image_url: null,
      profile_background_image_url_https: null,
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1384202985639604226/-qUtqxKk_normal.png",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1384202985639604226/-qUtqxKk_normal.png",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: false,
      following: true,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none",
      withheld_in_countries: [],
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: "en",
  },
  {
    created_at: "Mon Apr 19 23:05:10 +0000 2021",
    id: 1384281950773411800,
    id_str: "1384281950773411845",
    full_text: "Let’s give it a try!",
    truncated: false,
    display_text_range: [0, 20],
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [],
      urls: [],
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: 1384281872344047600,
    in_reply_to_status_id_str: "1384281872344047617",
    in_reply_to_user_id: 1379970996350947300,
    in_reply_to_user_id_str: "1379970996350947335",
    in_reply_to_screen_name: "sredouane10",
    user: {
      id: 1379970996350947300,
      id_str: "1379970996350947335",
      name: "Saïd",
      screen_name: "sredouane10",
      location: "",
      description: "",
      url: null,
      entities: {
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 2,
      friends_count: 10,
      listed_count: 0,
      created_at: "Thu Apr 08 01:35:11 +0000 2021",
      favourites_count: 0,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 5,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "F5F8FA",
      profile_background_image_url: null,
      profile_background_image_url_https: null,
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1384202985639604226/-qUtqxKk_normal.png",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1384202985639604226/-qUtqxKk_normal.png",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: false,
      following: true,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none",
      withheld_in_countries: [],
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: "en",
  },
];

module.exports = mockData;
